config/routes.rb
MovieOMatic2::Application.routes.draw do
  resources :screenings

  root :to => 'movies#chart'

  resources :movies do
    member do
        get :chart
    end
    get :chart, :on => :collection
    get :autocomplete, :on => :collection
  end

  match 'movies/:first/:second' => 'movies#chart'
  match 'about' => 'other#about', :as => :about

end

app/models/screening.rb
#!/usr/bin/env ruby
#coding: utf-8

class Screening < ActiveRecord::Base
  def self.get_percent_filling_by_movie_id(movieID)
    #Screening.order("time_before_screening").find_all_by_movie_id(movieID)

    # PostgreSQL
    find_by_sql(["select cast(floor(time_before_screening::real/1) as decimal(7,1)) as tbs, avg(seats_taken::real/seats_total) as obsadenost from screenings where movie_id = ? group by tbs;", movieID])

    #MySQL
    #find_by_sql(["select cast(floor(time_before_screening/1) as decimal(7,1)) as tbs, avg(seats_taken/seats_total) as obsadenost from screenings where movie_id = ? group by tbs;", movieID])
  end
end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController
  # GET /screenings
  # GET /screenings.xml
  def index
    @screenings = Screening.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @screenings }
    end
  end

  # GET /screenings/1
  # GET /screenings/1.xml
  def show
    @screening = Screening.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @screening }
    end
  end

  # GET /screenings/new
  # GET /screenings/new.xml
  def new
    @screening = Screening.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @screening }
    end
  end

  # GET /screenings/1/edit
  def edit
    @screening = Screening.find(params[:id])
  end

  # POST /screenings
  # POST /screenings.xml
  def create
    @screening = Screening.new(params[:screening])

    respond_to do |format|
      if @screening.save
        format.html { redirect_to(@screening, :notice => 'Screening was successfully created.') }
        format.xml  { render :xml => @screening, :status => :created, :location => @screening }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @screening.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /screenings/1
  # PUT /screenings/1.xml
  def update
    @screening = Screening.find(params[:id])

    respond_to do |format|
      if @screening.update_attributes(params[:screening])
        format.html { redirect_to(@screening, :notice => 'Screening was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @screening.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /screenings/1
  # DELETE /screenings/1.xml
  def destroy
    @screening = Screening.find(params[:id])
    @screening.destroy

    respond_to do |format|
      format.html { redirect_to(screenings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/views/screenings/_form.html.erb
<%= form_for(@screening) do |f| %>
  <% if @screening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screening.errors.count, "error") %> prohibited this screening from being saved:</h2>

      <ul>
      <% @screening.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie %><br />
    <%= f.text_field :movie %>
  </div>
  <div class="field">
    <%= f.label :time_before_screening %><br />
    <%= f.text_field :time_before_screening %>
  </div>
  <div class="field">
    <%= f.label :seats_taken %><br />
    <%= f.text_field :seats_taken %>
  </div>
  <div class="field">
    <%= f.label :seats_total %><br />
    <%= f.text_field :seats_total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screenings/edit.html.erb
<h1>Editing screening</h1>

<%= render 'form' %>

<%= link_to 'Show', @screening %> |
<%= link_to 'Back', screenings_path %>

app/views/screenings/index.html.erb
<div class="container">
    <br>
    <div class="header">Screenings</div>
</div>

<table class="container">
  <tr>
    <th>Movie</th>
    <th>Time before screening</th>
    <th>Seats taken</th>
    <th>Seats total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @screenings.each do |screening| %>
  <tr>
    <td><%= screening.movie_id %></td>
    <td><%= screening.time_before_screening %></td>
    <td><%= screening.seats_taken %></td>
    <td><%= screening.seats_total %></td>
    <td><%= link_to 'Show', screening %></td>
    <td><%= link_to 'Edit', edit_screening_path(screening) %></td>
    <td><%= link_to 'Destroy', screening, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Screening', new_screening_path %>

app/views/screenings/new.html.erb
<h1>New screening</h1>

<%= render 'form' %>

<%= link_to 'Back', screenings_path %>

app/views/screenings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Movie:</b>
  <%= @screening.movie %>
</p>

<p>
  <b>Time before screening:</b>
  <%= @screening.time_before_screening %>
</p>

<p>
  <b>Seats taken:</b>
  <%= @screening.seats_taken %>
</p>

<p>
  <b>Seats total:</b>
  <%= @screening.seats_total %>
</p>


<%= link_to 'Edit', edit_screening_path(@screening) %> |
<%= link_to 'Back', screenings_path %>