config/routes.rb
MovieOMatic2::Application.routes.draw do
  resources :screenings

  root :to => 'movies#chart'

  resources :movies do
    member do
        get :chart
    end
    get :chart, :on => :collection
    get :autocomplete, :on => :collection
  end

  match 'movies/:first/:second' => 'movies#chart'
  match 'about' => 'other#about', :as => :about

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.xml
  def index
    @query = params[:q]
    @movies = if @query.blank?
                Movie.all
              else
                Movie.name_starts_with(@query)
              end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @movies }
    end
  end

  def chart
    @movies = Movie.get_movies_ordered_by_screening_count
    if params[:first].nil?
      if @first.nil?
        @first = Movie.find(119)
      end
    else
      @first = Movie.find(params[:first])
    end
      
    if params[:second].nil?
      if @second.nil?
        @second = Movie.find(123)
      end
    else
      @second = Movie.find(params[:second])
    end

    respond_to do |format|
      format.html # chart.html.erb
      format.xml  { render :xml => @movies }
    end
  end

  def autocomplete
    matches = Movie.name_starts_with(params[:term]).collect(&:name)
    render :json => matches
  end

  # GET /movies/1
  # GET /movies/1.xml
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.xml
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.xml
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to(@movie, :notice => 'Movie was successfully created.') }
        format.xml  { render :xml => @movie, :status => :created, :location => @movie }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.xml
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to(@movie, :notice => 'Movie was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.xml
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to(movies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/chart.html.erb
<div class="entry">
    <h2 class="title">Štatistiky</h2>
</div>

<script type="text/javascript">
$(document).ready(function() {
  $('#menu_select_1').bind('change', function() { window.location.href = $(this).val() });
});
</script>

<script type="text/javascript">
$(document).ready(function() {
  $('#menu_select_2').bind('change', function() { window.location.href = $(this).val() });
});
</script>

<%
    array1 = []
	@movies.each do |movie|
 		array1 << [movie.name, chart_movies_url(:first => @first.id, :second => movie.id)]
	end

	array2 = []
	@movies.each do |movie|
 		array2 << [movie.name, chart_movies_url(:first => movie.id, :second => @second.id)]
	end
%>

<script type="text/javascript" charset="utf-8">
  $(function() {
    new Highcharts.Chart({
        chart: {
            renderTo: "movies_chart",
            defaultSeriesType: 'spline',
            backgroundColor: "#F0E9E9"
        },
        tooltip: {
            formatter: function() {
                return 'Predstavenie <b>'+ this.series.name +'</b><br>Čas pred predstavením <b>'
                        + this.x +'h</b><br>Obsadenosť <b>'+ this.y +'%</b>';
        }
        },
        title: {
            text: "Obsadenosť kinosál podľa času pred predstavením"
        },
        plotOptions: {
            spline: {
                lineWidth: 4,
                states: {
                    hover: {
                        lineWidth: 5
                    }
                },
                marker: {
                    enabled: false,
                    states: {
                        hover: {
                            enabled: true,
                            symbol: 'circle',
                            radius: 5,
                            lineWidth: 1
                        }
                    }
                }
            }
        },
        xAxis: {
            type: "number",
            title: {
                text: "Cas pred predstavenim (h)"
            },
            reversed: true
        },
        yAxis: {
            title: {
                text: "Naplnenost (%)"
            },
            min: 0
        },
        series: [
		{
            name: "<%= Movie.get_movie_name_by_id(@first.id) %>",
            data: [
            <% Screening.get_percent_filling_by_movie_id(@first.id).each do |vec| %>
                [
				<%= vec.attributes["tbs"].to_f %>
				<%= "," %>
                <%= (((vec.attributes["obsadenost"].to_f) * 10**2).round / (10**2).to_f)*100 %>
				]
				<%= "," %>
            <%end%>
            ]
        },
        {
            name: "<%= Movie.get_movie_name_by_id(@second.id) %>",
            data: [
            <% Screening.get_percent_filling_by_movie_id(@second.id).each do |vec| %>
                [
				<%= vec.attributes["tbs"].to_f %>
				<%= "," %>
				<%= (((vec.attributes["obsadenost"].to_f) * 10**2).round / (10**2).to_f)*100 %>
				]
				<%= "," %>
            <%end%>
            ]
        }
		]
    });
  });
</script>

<div style="clear: both;">&nbsp;</div>
<div class="entry">
    <table class="container">
      <tr>
        <td width="80">Prvy film:</td>
        <td>
          <%= select_tag(:menu_select_2, options_for_select(array2, chart_movies_url(:first => @first.id, :second => @second.id))) %>
        </td>
      </tr>
      <tr>
        <td width="80">Druhy film:</td>
        <td>
          <%= select_tag(:menu_select_1, options_for_select(array1, chart_movies_url(:first => @first.id, :second => @second.id))) %>
        </td>
      </tr>
</table>
</div>

<div style="clear: both;">&nbsp;</div>
<div class="entry">
  <div id="movies_chart" class="movies_chart" style="width:100%; height:300px;"></div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="entry">
    <h2 class="title">Filmy</h2>
</div>

<div style="clear: both;">&nbsp;</div>
<div class="entry">
<table class="container">
  <tr>
    <td>
      <%= form_tag movies_path, :method => :get do |f| %>
        <%= text_field_tag :q, @query, 'data-autocomplete-url' => autocomplete_movies_path %>
        <%= submit_tag 'Search' %>
      <% end %>
    </td>
  </tr>
</table>
</div>

<div style="clear: both;">&nbsp;</div>
<div class="entry">
  <table>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>