config/routes.rb
MovieOMatic2::Application.routes.draw do
  resources :screenings

  root :to => 'movies#chart'

  resources :movies do
    member do
        get :chart
    end
    get :chart, :on => :collection
    get :autocomplete, :on => :collection
  end

  match 'movies/:first/:second' => 'movies#chart'
  match 'about' => 'other#about', :as => :about

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Brown Stone
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20100928

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery-1.4.2.min", "rails", "highcharts" %>
<title>Brown Stone   by Free CSS Templates</title>
<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-15160065-2']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
</head>
<body>
<div id="wrapper">
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
					<div class="post">
                        <%= yield %>
					</div>
					<div style="clear: both;">&nbsp;</div>
				</div>
				<!-- end #content -->
				<div id="sidebar">
					<div id="logo">
						<h1><a href=<%= root_path %>>Filmy</a></h1>
						<div style="clear: both;">&nbsp;</div>
						<p>Štatistiky obsadenosti</p>
					</div>
					<div id="menu">
						<ul>
                            <li><a href=<%= root_path %>>Štatistiky</a></li>
							<li><a href=<%= movies_path %>>Filmy</a></li>
							<li><a href=<%= about_path %>>O projekte</a></li>
						</ul>
					</div>
				</div>
				<!-- end #sidebar -->
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page -->
</div>
<div id="footer">
	<p>Copyright (c) 2011 movie-o-matic.heroku.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">CSS Templates</a>.</p>
</div>
<!-- end #footer -->
</body>
</html>